# optional area within which the objects should exist
geometry_msgs/Polygon area
# optional type of object to return
string type
---
# if false; query was not able to executed
# note: could be true with an empty list of objects returned
bool success
ropod_ros_msgs/ObjectList objects
---
