# variable indicating docking command [1: dock; 2: release; 3: stop (not implemented); 4: Horz positive motion; 5: Horz negative motion; 6: Vert positive motion; 7: Vert negative motion]
uint8 DOCKING_COMMAND_DOCK = 1
uint8 DOCKING_COMMAND_RELEASE = 2
uint8 DOCKING_COMMAND_STOP = 3
uint8 DOCKING_COMMAND_HORIZONTAL_FORWARD = 4
uint8 DOCKING_COMMAND_HORIZONTAL_BACKWARD = 5
uint8 DOCKING_COMMAND_VERTICAL_FORWARD = 6
uint8 DOCKING_COMMAND_VERTICAL_BACKWARD = 7

uint8 docking_command
